---
title: "HDD"
output: html_document
date: "2023-09-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,RWiener, tidybayes, posterior, furrr)

library(patchwork)


```

## R Markdown



```{r}
library(cmdstanr)

mod <- cmdstan_model(here::here("HDMM_rng.stan"))

out <- mod$sample(
  data = list(
    N = 400,
    alpha_in = 1.25,
    tau_in = 0.2,
    beta_in = 0.7,
    delta_in = -0.3
  ),
  parallel_chains = 4
)

flextable::flextable(data.frame(out$summary()) %>% mutate_if(is.numeric, round,2))
```

```{r}
trials = 500
alpha = 2
delta = 0
beta = 0.5
tau = 0.1


parameters = data.frame(alpha,delta,beta,tau, trials)

data = rwiener(n = trials,
        alpha = alpha,
        delta = delta,
        beta = beta,
        tau = tau)

data_stan = list(Nu = nrow(data %>% filter(resp == "upper")),
                 Nl = nrow(data %>% filter(resp == "lower")),
                 RTu = data %>% filter(resp == "upper") %>% .$q,
                 RTl = data %>% filter(resp == "lower") %>% .$q,
                 minRT = min(data$q),
                 run_estimation = 1)


mod = cmdstanr::cmdstan_model(here::here("HDDM.stan"))


fit <- mod$sample(
    data = data_stan,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12)




rt_pattern <- "out\\[\\d+,1\\]"
choice_pattern <- "out\\[\\d+,2\\]"


Rts = fit$summary() %>%
  filter(grepl(rt_pattern, variable))


Rts = as_draws_df(fit$draws()) %>%
  select(matches(rt_pattern))

Rts %>% slice(sample(1:4000,10)) %>% pivot_longer(everything()) %>% ggplot(aes(x = value))+geom_histogram()

choice = fit$summary() %>%
  filter(grepl(choice_pattern, variable))

choice = as_draws_df(fit$draws()) %>%
  select(matches(choice_pattern))


posteriors = as_draws_df(fit) %>% dplyr::select(any_of(names(parameters))) %>% mutate(prior = F)
priors = as_draws_df(fit) %>% dplyr::select(starts_with("prior_")) %>% rename_with(~gsub("^prior_", "", .), everything()) %>% mutate(prior = T)

rbind(posteriors,priors) %>% 
  pivot_longer(cols = -prior) %>% 
  ggplot(aes(x = value, fill = prior))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  facet_wrap(~name, scales = "free")+
  geom_vline(data = parameters %>% select(-trials) %>% pivot_longer(everything()), aes(xintercept = value))


draws = 10
#pp_check
as_draws_df(fit$draws()) %>%
  select(matches(rt_pattern)) %>% slice(sample(1:4000,draws)) %>% 
  pivot_longer(everything()) %>% mutate(estimated = TRUE, slice = rep(1:trials,draws)) %>% 
  ggplot()+
  geom_density(aes(x = value, group = slice), color = "lightblue")+
  geom_density(data = data %>% mutate(estimated = FALSE), aes(x = q), color = "red")+
  theme_classic()

```

```{r the RLDMM only in stan}
library(cmdstanr)

mod <- cmdstan_model(here::here("RLHDMM_rng.stan"))
N = 200
u = rep(c(rbinom(50,1,0.8),rbinom(50,1,0.2),rbinom(50,1,0.8),rbinom(50,1,0.5)),N/200)

out <- mod$sample(
  data = list(
    N = N,
    alpha_in = 1.25,
    tau_in = 0.2,
    beta_in = 0.7,
    delta_in = 0.1,
    u = u,
    lr_in = 0.2
  ),
  parallel_chains = 4
)

flextable::flextable(data.frame(out$summary()) %>% mutate_if(is.numeric, round,2) %>% head(20))

library(posterior)
as_draws_df(out$draws()) %>% select(matches("rt2\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number < 150) %>% ggplot(aes(x = value))+geom_histogram()

as_draws_df(out$draws()) %>% select(matches("rt2\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number > 150) %>% ggplot(aes(x = value))+geom_histogram()



as_draws_df(out$draws()) %>% select(matches("idx3\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number < 150) %>% ggplot(aes(x = value))+geom_histogram()


as_draws_df(out$draws()) %>% select(matches("idx3\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number > 150) %>% ggplot(aes(x = value))+geom_histogram()

```

```{r the RLDMM in r}
library(cmdstanr)

mod <- cmdstan_model(here::here("RLHDMM_rng.stan"))
N = 600
u = rep(c(rbinom(50,1,0.8),rbinom(50,1,0.2),rbinom(50,1,0.8),rbinom(50,1,0.5)),N/200)

alpha = 2
delta = 2
beta = 0.5
tau = 0.1
lr = 0.3
e0 = 0.5
expectation = array(NA, N+1)
uncertainty = array(NA, N)
expectation[1] = e0

resp = data.frame()
for(i in 1:N){
  
  uncertainty[i] = (expectation[i]-(1-expectation[i]))*delta
  
  resp1 = rwiener(n = 1,
        alpha = alpha,
        delta = uncertainty[i],
        beta = beta,
        tau = tau)
  
  expectation[i+1] = expectation[i]+lr*(u[i]-expectation[i])
  
  resp = rbind(resp,resp1)
}

resp$u = u
resp$expectation = expectation[1:N]
resp$uncertainty = uncertainty[1:N]

resp$trial = 1:N

resp %>% ggplot(aes(x = uncertainty, y = q))+geom_point()

resp %>% mutate(resp = ifelse(resp == "upper",1,0)) %>% ggplot()+
  geom_point(aes(x = 1:N, y = u),alpha = 0.5, col = "red")+
  geom_point(aes(x = 1:N, y = resp),alpha = 0.5, col = "green")+
  theme_classic()+
  geom_line(aes(x=1:N, y = expectation))



resp = resp %>% mutate(resp2 = ifelse(resp == "upper",1,0))


mod = cmdstanr::cmdstan_model(here::here("RLDDM.stan"))



data_stan = list(Nu = nrow(resp %>% filter(resp == "upper")),
                 Nl = nrow(resp %>% filter(resp == "lower")),
                 RTu = resp %>% filter(resp == "upper") %>% .$q,
                 RTl = resp %>% filter(resp == "lower") %>% .$q,
                 minRT = min(resp$q),
                 run_estimation = 1,
                 trials = nrow(resp),
                 u = resp$u,
                 indexupper = resp %>% filter(resp == "upper") %>% .$trial,
                 indexlower = resp %>% filter(resp == "lower") %>% .$trial,
                 resp = c(resp$resp2,0))


fit1 <- mod$sample(
    data = data_stan,
    chains = 4,
    iter_warmup = 2000,
    iter_sampling = 2000,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 100
    )



fit1


flextable::flextable(data.frame(out$summary()) %>% mutate_if(is.numeric, round,2) %>% head(20))

library(posterior)
as_draws_df(out$draws()) %>% select(matches("rt2\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number < 150) %>% ggplot(aes(x = value))+geom_histogram()

as_draws_df(out$draws()) %>% select(matches("rt2\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number > 150) %>% ggplot(aes(x = value))+geom_histogram()



as_draws_df(out$draws()) %>% select(matches("idx3\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number < 150) %>% ggplot(aes(x = value))+geom_histogram()


as_draws_df(out$draws()) %>% select(matches("idx3\\[\\d+\\]")) %>% pivot_longer(everything())%>%
  mutate(number = as.numeric(gsub(".*\\[(\\d+)\\].*", "\\1", name))) %>% filter(number > 150) %>% ggplot(aes(x = value))+geom_histogram()

```

```{r}


agent = function(parameters){
set.seed(222)  
  
trials_per_reversal = parameters$trials_per_reversal
n_reversals = parameters$n_reversals

u = rep(c(rbinom(trials_per_reversal,1,0.8),rbinom(trials_per_reversal,1,0.2)),n_reversals)


N = length(u)

alpha = parameters$alpha
delta = parameters$delta
beta = parameters$beta
tau = parameters$tau
lr = parameters$lr
e0 = parameters$e0
zeta = parameters$zeta


expectation = array(NA, N+1)
uncertainty = array(NA, N)
real_resp = array(NA, N)

expectation[1] = e0

resp = data.frame()
for(i in 1:N){
  
  uncertainty[i] = (expectation[i]-(1-expectation[i]))*delta
  
  resp1 = rwiener(n = 1,
        alpha = alpha,
        delta = uncertainty[i],
        beta = beta,
        tau = tau)
  
  expectation[i+1] = expectation[i]+lr*(u[i]-expectation[i])
  
  real_resp[i] = rbinom(1,1,(expectation[i]^zeta)/((expectation[i]^zeta)+(1-expectation[i])^zeta))
    
  resp = rbind(resp,resp1)
}

resp$u = u
resp$expectation = expectation[1:N]
resp$uncertainty = uncertainty[1:N]
resp$real_resp = real_resp

resp$trial = 1:N

resp %>% ggplot(aes(x = trial, y = expectation))+geom_line()+geom_point(aes(x = trial, y = u))

resp = resp %>% mutate(resp2 = ifelse(resp == "upper",1,0))

resp = resp %>% mutate(correct = ifelse(real_resp == u, 1, 0))

agg = data.frame(pcorrect =  sum(resp$correct)/N,
                 correct = sum(resp$correct),
                 lr = lr,
                 zeta = zeta,
                 trials = N,
                 n_r = n_reversals,
                 t_p_r = trials_per_reversal)


return(list(agg))
}


n_reversals = seq(1,5,length.out = 5)
#n_reversals = seq(5,length.out = 1)

trials_per_reversal = seq(20,50, by = 10)
#trials_per_reversal = seq(20, length.out = 1)


alpha = seq(1, length.out = 1)

lr = seq(0.01,0.99, length.out = 10)
zeta = seq(0.1,10, length.out = 10)


delta  = seq(1,length.out = 1)

beta = seq(0.5,length.out = 1)

tau = seq(0.1, length.out = 1)

e0 = seq(0.5, length.out = 1)

replicate = 1

parameters = expand.grid(n_reversals = n_reversals,
                         lr= lr,
                         zeta = zeta,
                         alpha = alpha,
                         delta = delta,
                         beta = beta,
                         tau = tau,
                         e0 = e0,
                         replicate = replicate,
                         trials_per_reversal = trials_per_reversal) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)


agent(parameters = data.frame(n_reversals = 10,
                              trials_per_reversal = 10,
                              alpha = 1,
                              lr = 0.5,
                              delta = 1,
                              beta = 0.5,
                              tau = 0.1,
                              e0 = 0.5,
                              zeta = 10,
                              id = 2))
```


```{r, fig.height=10,fig.width=10}
cores = availableCores()-2

plan(multisession, workers = cores)

results <- future_map(data_list, ~agent(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

params = map_dfr(results, 1)

params %>% ggplot(aes(x = lr, y = zeta,col = pcorrect))+
  geom_jitter()+
  facet_wrap(~trials)+
  theme_classic()+
  scale_color_continuous(type = "viridis")

params %>% mutate() %>% ggplot(aes(y = lr, x = zeta, col = pcorrect))+
  geom_jitter()+
  facet_wrap(t_p_r~n_r, ncol = 5, labeller = label_both)+
  scale_color_continuous(type = "viridis")

params %>% group_by(t_p_r, n_r,lr,zeta) %>% summarize(mean = mean(pcorrect)) %>% ggplot(aes(y = lr, x = zeta, col = mean))+
  geom_jitter()+
  facet_wrap(t_p_r~n_r, ncol = 5, labeller = label_both)+
  scale_color_continuous(type = "viridis")

params %>% group_by(t_p_r, n_r,lr,zeta) %>% summarize(mean = mean(pcorrect)) %>% 
  ggplot(aes(y = lr, x = zeta, fill = mean))+
  geom_raster()+
  facet_wrap(t_p_r~n_r, ncol = 5, labeller = label_both)+
  scale_fill_continuous(type = "viridis",)+
  theme_classic()


params %>% group_by(t_p_r, n_r,lr,zeta) %>% summarize(mean = mean(pcorrect)) %>% 
  mutate(mean = round(mean,22)) %>% mutate(mean = ifelse(mean < max(params$pcorrect)-0.05, NA, mean)) %>% 
  ggplot(aes(y = lr, x = zeta, fill = mean))+
  geom_raster()+
  facet_wrap(t_p_r~n_r, ncol = 5, labeller = label_both)+
  scale_fill_continuous(type = "viridis",)+
  theme_classic()

```



```{r, fig.height=7,fig.width=7, volatile kalman filter}
agent2 = function(parameters){
seed = parameters$seed
set.seed(seed)  
  
trials_per_reversal = parameters$trials_per_reversal
n_reversals = parameters$n_reversals

u = c(rbinom(50,1,0.8),
      rep(c(rbinom(trials_per_reversal/2,1,0.2),
          rbinom(trials_per_reversal/2,1,0.8)),n_reversals),
      rbinom(50,1,0.2))

# fifty_trials = 100
# 
# fifty = rbinom(fifty_trials,1,0.5)
# 
# u = c(fifty,u,fifty)
# 
# desired_prob = rep(c(rep(0.8,trials_per_reversal),rep(0.2,trials_per_reversal)),n_reversals)
# 
# desired_prob = c(rep(0.5,fifty_trials), desired_prob,rep(0.5,fifty_trials))

N = length(u)

omega = parameters$omega
v0 = parameters$v0
w0 = parameters$w0
m0 = parameters$m0

lambda = parameters$lambda

zeta = parameters$zeta


k = array(NA, N+1)
a = array(NA, N+1)
m = array(NA, N+1)
v = array(NA, N+1)
w = array(NA, N+1)
w2 = array(NA, N+1)
real_resp = array(NA, N+1)

w[1] = w0
v[1] = v0
m[1] = m0

s = function(x){
  return(1/(1+exp(-x)))
}

agg = tryCatch({
    for(i in 1:N){
    
    k[i+1] = (w[i]+v[i])/(w[i]+v[i]+omega)
    a[i+1] = sqrt((w[i]+v[i]))
    m[i+1] = m[i]+a[i+1]*(u[i]-s(m[i]))
    
    w2[i] = (1-k[i+1])*(w[i])
    
    w[i+1] = (1-k[i+1])*(w[i]+v[i])
    
    v[i+1] = v[i]+lambda*((m[i+1]-m[i])^2+w[i]+w[i+1]-2*w2[i]-v[i])
    
    real_resp[i] = rbinom(1,1,(s(m[i])^zeta)/((s(m[i])^zeta)+(1-s(m[i]))^zeta))
    
    }
    resp = data.frame(k = k,a = a, m = m, w2 = w2, w = w, v = v, resp = real_resp)
    resp$u = c(u,NA)
    resp$trial = 1:(N+1)
    resp = resp %>% mutate(correct = ifelse(real_resp == u, 1, 0))
# 

    resp = resp[1:N,]
    agg = data.frame(pcorrect =  sum(resp$correct)/N,
                     correct = sum(resp$correct),
                     omega = omega,
                     lambda = lambda,
                     zeta = zeta,
                     trials = N,
                     seed = seed,
                     n_r = n_reversals,
                     t_p_r = trials_per_reversal)
      
      
    }, warning=function(w) {
        ## do something about the warning, maybe return 'NA'
        return(data.frame(pcorrect = NA,
                     correct = NA,
                     omega = omega,
                     lambda = lambda,
                     zeta = zeta,
                     seed = seed,
                     trials = N,
                     n_r = n_reversals,
                     t_p_r = trials_per_reversal))
})



#resp$desired_prob = c(desired_prob,NA)


# 
# pred = resp %>% ggplot(aes(x = trial, y = s(m)))+
#   geom_line()+
#   geom_point(aes(x = trial, y = u), col = "red", alpha = 0.5)+
#   geom_point(aes(x = trial, y = resp), col = "green", alpha = 0.5)+
#   theme_classic()#+
#   #geom_line(aes(x = trial, y = desired_prob))
# 
# vol = resp %>% ggplot(aes(x = trial, y = v))+
#   geom_line()+
#   theme_classic()
# 
# learn = resp %>% ggplot(aes(x = trial, y = a))+
#   geom_line()+
#   theme_classic()
# 
# 
# plot = learn/vol/pred

# 
# resp = resp %>% mutate(resp2 = ifelse(resp == "upper",1,0))
# 


return(list(agg))
}
```


```{r volatile kalman filter, fig.height=7,fig.width=7}
v = agent2(parameters = data.frame(n_reversals = 5,
                              trials_per_reversal = 20,
                              omega = 1,
                              v0 = 0.1,
                              seed = 123,
                              w0 = 0.1,
                              m0 = 0.5,
                              lambda = 1,
                              zeta = 5,
                              id = 2))



n_reversals = seq(10,length.out = 1)
#n_reversals = seq(5,length.out = 1)

trials_per_reversal = seq(40, length.out = 1)
#trials_per_reversal = seq(20, length.out = 1)


omega = seq(0.1,20, length.out = 25)
lambda = seq(0.01,5, length.out = 25)


v0 = seq(0.1, length.out = 1)

m0 = seq(0.5, length.out = 1)

w0 = seq(0.1, length.out = 1)

zeta = seq(5,5, by = 1)

seed = sample(round(rnorm(1000,1000,100),0),25,replace = F)

replicate = 1

parameters = expand.grid(n_reversals = n_reversals,
                         omega= omega,
                         lambda = lambda,
                         v0 = v0,
                         w0 = w0,
                         m0 = m0,
                         seed = seed,
                         zeta = zeta,
                         replicate = replicate,
                         trials_per_reversal = trials_per_reversal) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)


cores = availableCores()-100

plan(multisession, workers = cores)

results <- future_map(data_list, ~agent2(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

params = map_dfr(results, 1)

params2 = na.omit(params)


## seed analysis

optimals = params2[params2$pcorrect == max(params2$pcorrect, na.rm = T) | params2$pcorrect > max(params2$pcorrect, na.rm = T)-0.05,] 
optimal = params2[params2$pcorrect == max(params2$pcorrect, na.rm = T),]

params %>% group_by(t_p_r, n_r,omega,zeta,lambda, seed) %>% summarize(mean = mean(pcorrect)) %>% 
  mutate(mean = round(mean,2)) %>% 
  ggplot(aes(y = omega, x = lambda))+
  geom_raster(aes(fill = mean))+
  facet_wrap(~seed, labeller = label_both)+
  scale_fill_continuous(type = "viridis",)+
  theme_classic()+
  geom_point(data = optimals, size = 1)+
  geom_point(data = optimal, size = 2, col = "red")
  

params %>% group_by(t_p_r, n_r,omega,zeta,lambda) %>% summarize(mean = mean(pcorrect)) %>% 
  mutate(mean = round(mean,2)) %>% 
  ggplot(aes(y = omega, x = lambda, col = mean))+
  geom_jitter()+
  facet_wrap(~zeta, labeller = label_both)+
  scale_color_continuous(type = "viridis",)+
  theme_classic()


## trials analysis


optimals = params2[params2$pcorrect == max(params2$pcorrect, na.rm = T) | params2$pcorrect > max(params2$pcorrect, na.rm = T)-0.05,] 
optimal = params2[params2$pcorrect == max(params2$pcorrect, na.rm = T),]

params %>% group_by(t_p_r, n_r,omega,zeta,lambda, seed) %>% summarize(mean = mean(pcorrect)) %>% 
  mutate(mean = round(mean,2)) %>% mutate(mean = ifelse(mean < max(optimal$pcorrect)-0.05, NA, mean)) %>% 
  ggplot(aes(y = omega, x = lambda))+
  geom_raster(aes(fill = mean))+
  facet_wrap(t_p_r~n_r, labeller = label_both, ncol = length(n_reversals), nrow = length(trials_per_reversal))+
  scale_fill_continuous(type = "viridis",)+
  theme_classic()+
  geom_point(data = optimals, size = 1)+
  geom_point(data = optimal, size = 2, col = "red")


params %>% group_by(t_p_r, n_r,omega,zeta,lambda, seed) %>% summarize(mean = mean(pcorrect)) %>% 
  mutate(mean = round(mean,2)) %>% mutate(mean = ifelse(mean < max(optimal$pcorrect)-0.05, NA, mean)) %>% 
  ggplot(aes(y = omega, x = lambda))+
  geom_raster(aes(fill = mean))+
  facet_wrap(~seed, labeller = label_both)+
  scale_fill_continuous(type = "viridis",)+
  theme_classic()+
  geom_point(data = optimal, size = 2, col = "red")
```




```{r volatile kalman filter, fig.height=7,fig.width=7}
agent2 = function(parameters){
seed = parameters$seed
set.seed(seed)  
  
trials_per_reversal = parameters$trials_per_reversal
n_reversals = parameters$n_reversals

u = c(rbinom(50,1,0.8),
      rep(c(rbinom(trials_per_reversal/2,1,0.2),rbinom(trials_per_reversal/2,1,0.8)),n_reversals),
      rbinom(50,1,0.2))

# fifty_trials = 100
# 
# fifty = rbinom(fifty_trials,1,0.5)
# 
# u = c(fifty,u,fifty)
# 
# desired_prob = rep(c(rep(0.8,trials_per_reversal),rep(0.2,trials_per_reversal)),n_reversals)
# 
# desired_prob = c(rep(0.5,fifty_trials), desired_prob,rep(0.5,fifty_trials))

N = length(u)

omega = parameters$omega
v0 = parameters$v0
w0 = parameters$w0
m0 = parameters$m0

lambda = parameters$lambda

zeta = parameters$zeta


k = array(NA, N+1)
a = array(NA, N+1)
m = array(NA, N+1)
v = array(NA, N+1)
w = array(NA, N+1)
w2 = array(NA, N+1)
real_resp = array(NA, N+1)

w[1] = w0
v[1] = v0
m[1] = m0

s = function(x){
  return(1/(1+exp(-x)))
}

agg = tryCatch({
    for(i in 1:N){
    
    k[i+1] = (w[i]+v[i])/(w[i]+v[i]+omega)
    a[i+1] = sqrt((w[i]+v[i]))
    m[i+1] = m[i]+a[i+1]*(u[i]-s(m[i]))
    
    w2[i] = (1-k[i+1])*(w[i])
    
    w[i+1] = (1-k[i+1])*(w[i]+v[i])
    
    v[i+1] = v[i]+lambda*((m[i+1]-m[i])^2+w[i]+w[i+1]-2*w2[i]-v[i])
    
    real_resp[i] = rbinom(1,1,(s(m[i])^zeta)/((s(m[i])^zeta)+(1-s(m[i]))^zeta))
    
    }
    resp = data.frame(k = k,a = a, m = m, w2 = w2, w = w, v = v, resp = real_resp,u = c(u,0))
    resp$u = c(u,NA)
    resp$trial = 1:(N+1)
    resp = resp %>% mutate(correct = ifelse(real_resp == u, 1, 0))
# 

    resp = resp[1:N,]
    agg = data.frame(pcorrect =  sum(resp$correct)/N,
                     correct = sum(resp$correct),
                     omega = omega,
                     lambda = lambda,
                     zeta = zeta,
                     trials = N,
                     seed = seed,
                     n_r = n_reversals,
                     t_p_r = trials_per_reversal)
      
      return(resp)
    }, warning=function(w) {
        ## do something about the warning, maybe return 'NA'
        return(data.frame(pcorrect = NA,
                     correct = NA,
                     omega = omega,
                     lambda = lambda,
                     zeta = zeta,
                     seed = seed,
                     trials = N,
                     n_r = n_reversals,
                     t_p_r = trials_per_reversal))
})



#resp$desired_prob = c(desired_prob,NA)


# 
# pred = resp %>% ggplot(aes(x = trial, y = s(m)))+
#   geom_line()+
#   geom_point(aes(x = trial, y = u), col = "red", alpha = 0.5)+
#   geom_point(aes(x = trial, y = resp), col = "green", alpha = 0.5)+
#   theme_classic()#+
#   #geom_line(aes(x = trial, y = desired_prob))
# 
# vol = resp %>% ggplot(aes(x = trial, y = v))+
#   geom_line()+
#   theme_classic()
# 
# learn = resp %>% ggplot(aes(x = trial, y = a))+
#   geom_line()+
#   theme_classic()
# 
# 
# plot = learn/vol/pred

# 
# resp = resp %>% mutate(resp2 = ifelse(resp == "upper",1,0))
# 


return(list(resp))
}


agent2_rl = function(parameters){
seed = parameters$seed
set.seed(seed)  
  
trials_per_reversal = parameters$trials_per_reversal
n_reversals = parameters$n_reversals

u = c(rbinom(50,1,0.8),
      rep(c(rbinom(trials_per_reversal/2,1,0.2),rbinom(trials_per_reversal/2,1,0.8)),n_reversals),
      rbinom(50,1,0.2))

# fifty_trials = 100
# 
# fifty = rbinom(fifty_trials,1,0.5)
# 
# u = c(fifty,u,fifty)
# 
# desired_prob = rep(c(rep(0.8,trials_per_reversal),rep(0.2,trials_per_reversal)),n_reversals)
# 
# desired_prob = c(rep(0.5,fifty_trials), desired_prob,rep(0.5,fifty_trials))

N = length(u)

m0 = parameters$m0

alpha = parameters$alpha

zeta = parameters$zeta

m = array(NA, N+1)
real_resp = array(NA, N+1)

m[1] = m0

s = function(x){
  return(1/(1+exp(-x)))
}

agg = tryCatch({
    for(i in 1:N){
    
    m[i+1] = m[i]+alpha*(u[i]-m[i])

    real_resp[i] = rbinom(1,1,(s(m[i])^zeta)/((s(m[i])^zeta)+(1-s(m[i]))^zeta))
    
    }
    resp = data.frame(resp = real_resp,u = c(u,0))
    resp$u = c(u,NA)
    resp$trial = 1:(N+1)
    resp = resp %>% mutate(correct = ifelse(real_resp == u, 1, 0))
# 

    resp = resp[1:N,]
    
      return(resp)
    }, warning=function(w) {
        ## do something about the warning, maybe return 'NA'
        return(data.frame(pcorrect = NA,
                     correct = NA,
                     omega = omega,
                     lambda = lambda,
                     zeta = zeta,
                     seed = seed,
                     trials = N,
                     n_r = n_reversals,
                     t_p_r = trials_per_reversal))
})


return(list(resp))
}
rl = agent2_rl(parameters = data.frame(n_reversals = 5,
                              trials_per_reversal = 20,
                              seed = 123,
                              m0 = 0.5,
                              alpha = 0.3,
                              zeta = 5,
                              id = 2))


vkf = agent2(parameters = data.frame(n_reversals = 5,
                              trials_per_reversal = 20,
                              omega = 1,
                              v0 = 0.1,
                              seed = 123,
                              w0 = 0.1,
                              m0 = 0.5,
                              lambda = 1,
                              zeta = 5,
                              id = 2))


vkf %>% ggplot(aes(x = trial, y = u)) + geom_point() + geom_line(aes(x = trial, y = brms::inv_logit_scaled(m)))


mod_vkf = cmdstanr::cmdstan_model(here::here("stan_scripts","VKF.stan"))

data_stan_vkf = list(resp = vkf$resp, u = vkf$u, N = nrow(vkf))

fit_VKF <- mod_vkf$sample(
    data = data_stan_vkf,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 500
    )
fit_VKF


mod_rl = cmdstanr::cmdstan_model(here::here("stan_scripts","RL_normal.stan"))


fit_RL <- mod_rl$sample(
    data = data_stan_vkf,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 500
    )
fit_RL


loo::loo_compare(list(VKF = fit_VKF$loo(), RL = fit_RL$loo()))

mod_vkf = cmdstanr::cmdstan_model(here::here("stan_scripts","VKF.stan"))

data_stan_rl = list(resp = rl$resp, u = rl$u, N = nrow(rl))

fit_VKF <- mod_vkf$sample(
    data = data_stan_rl,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = 0.90,
    max_treedepth = 12,
    refresh = 500
    )
fit_VKF

posterior::as_draws_df(fit_VKF$draws()) %>% select(omega,zeta, lambda)

mcmc_pairs(posterior::as_draws_df(fit_VKF$draws()) %>% select(omega,zeta,lambda),
           np = nuts_params(fit_VKF))

color_scheme_set("blue")
mcmc_parcoord(posterior::as_draws_df(fit_VKF$draws()) %>% select(omega,zeta,lambda), np = nuts_params(fit_VKF))

mcmc_trace(fit_VKF$draws(variables = c("omega","lambda","zeta")), np = nuts_params(fit_VKF))

mod_rl = cmdstanr::cmdstan_model(here::here("stan_scripts","RL_normal.stan"))


fit_RL <- mod_rl$sample(
    data = data_stan_rl,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 500
    )
fit_RL


loo::loo_compare(list(VKF = fit_VKF$loo(), RL = fit_RL$loo()))


```

```{r vkf parameter recovery}

vkf_parameter_recovery = function(parameters){
  
  vkf = agent2(parameters = data.frame(n_reversals = parameters$n_reversals,
                              trials_per_reversal = parameters$trials_per_reversal,
                              omega = parameters$omega,
                              v0 = parameters$v0,
                              seed = parameters$seed,
                              w0 = parameters$w0,
                              m0 = parameters$m0,
                              lambda = parameters$lambda,
                              zeta = parameters$zeta,
                              id = parameters$id)) 
  
  data_stan_vkf = list(resp = vkf$resp, u = vkf$u, N = nrow(vkf))

  
  fit_VKF <- mod_vkf$sample(
      data = data_stan_vkf,
      chains = 4,
      parallel_chains = 4,
      adapt_delta = 0.9,
      max_treedepth = 12,
      refresh = 500
      )
    


  posteriors = as_draws_df(fit_VKF$summary()) %>% dplyr::filter(variable %in% names(parameters))
  
  diag = data.frame(fit_VKF$diagnostic_summary(), id = parameters$id)
  
  data = posteriors %>% mutate(real_lambda = parameters$lambda,
                               real_omega = parameters$omega,
                               real_zeta = parameters$zeta,
                               n_reversals = parameters$n_reversals,
                               trials_per_reversal = parameters$trials_per_reversal,
                               id = parameters$id)
  return(list(data, diag))

}



n_reversals = seq(2,10,length.out = 9)
#n_reversals = seq(5,length.out = 1)

trials_per_reversal = seq(10,50, length.out = 5)
#trials_per_reversal = seq(20, length.out = 1)


lambda = seq(0.1,1.5, length.out = 5)

omega = seq(0.1,10, length.out = 5)

zeta = seq(1,10, length.out = 5)

seed = 123

replicate = 1

w0 = 0.1
v0 = 0.1
m0 = 0.5

parameters = expand.grid(n_reversals = n_reversals,
                         zeta = zeta,
                         w0 = w0,
                         v0 = v0,
                         seed = seed,
                         m0 = m0,
                         lambda = lambda,
                         omega = omega,
                         replicate = replicate,
                         trials_per_reversal = trials_per_reversal) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)
```

```{r}
qq = vkf_parameter_recovery(data_list[[50]])

cores = availableCores()-108

plan(multisession, workers = cores)

possfit_model = possibly(.f = vkf_parameter_recovery, otherwise = "Error")

results <- future_map(data_list, ~possfit_model(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

error_indices <- which(results == "Error")

unique(error_indices)

results2 = results[results != "Error"]
```



```{r, fig.height=10,fig.width=10}
params = map_dfr(results2,1)

params %>% filter(variable == "omega") %>% 
        ggplot(aes(x = mean, y = real_omega, col = real_lambda))+
        facet_grid(n_reversals~trials_per_reversal, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point()+geom_abline(slope = 1, intercept = 0)+
  coord_cartesian(ylim = c(-1, 10), xlim = c(-1,10))


params %>% filter(variable == "lambda") %>% 
        ggplot(aes(x = mean, y = real_lambda, col = real_omega))+
        facet_grid(n_reversals~trials_per_reversal, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point()+geom_abline(slope = 1, intercept = 0)+
  coord_cartesian(ylim = c(0, 1.5), xlim = c(0,1.5))


params %>% filter(variable == "omega") %>% 
        ggplot(aes(x = mean, y = real_omega))+
        facet_grid(n_reversals~trials_per_reversal, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point()+geom_abline(slope = 1, intercept = 0)+
  coord_cartesian(ylim = c(-1, 10), xlim = c(-1,10))


params %>% filter(variable == "lambda") %>% 
        ggplot(aes(x = mean, y = real_lambda))+
        facet_grid(n_reversals~trials_per_reversal, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point()+geom_abline(slope = 1, intercept = 0)+
  coord_cartesian(ylim = c(0, 1.5), xlim = c(0,1.5))


```



```{r parameter recovery}

mod = cmdstanr::cmdstan_model(here::here("RLDDM.stan"))


param_recov = function(parameters){

  
N = parameters$N
u = rep(c(rbinom(25,1,0.8),rbinom(25,1,0.2)),N/50)

alpha = parameters$alpha
delta = parameters$delta
beta = parameters$beta
tau = parameters$tau
lr = parameters$lr
e0 = parameters$e0

expectation = array(NA, N+1)
uncertainty = array(NA, N)
expectation[1] = e0

resp = data.frame()
for(i in 1:N){
  
  uncertainty[i] = (expectation[i]-(1-expectation[i]))*delta
  
  resp1 = rwiener(n = 1,
        alpha = alpha,
        delta = uncertainty[i],
        beta = beta,
        tau = tau)
  
  expectation[i+1] = expectation[i]+lr*(u[i]-expectation[i])
  
  resp = rbind(resp,resp1)
}

resp$u = u
resp$expectation = expectation[1:N]
resp$uncertainty = uncertainty[1:N]

resp$trial = 1:N


resp = resp %>% mutate(resp2 = ifelse(resp == "upper",1,0))


data_stan = list(Nu = nrow(resp %>% filter(resp == "upper")),
                 Nl = nrow(resp %>% filter(resp == "lower")),
                 RTu = resp %>% filter(resp == "upper") %>% .$q,
                 RTl = resp %>% filter(resp == "lower") %>% .$q,
                 minRT = min(resp$q),
                 run_estimation = 1,
                 trials = nrow(resp),
                 u = resp$u,
                 indexupper = resp %>% filter(resp == "upper") %>% .$trial,
                 indexlower = resp %>% filter(resp == "lower") %>% .$trial,
                 resp = c(resp$resp2,0))


fit1 <- mod$sample(
    data = data_stan,
    chains = 4,
    iter_warmup = 2000,
    iter_sampling = 2000,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 500
    )


fit1


posteriors = as_draws_df(fit1$summary()) %>% dplyr::filter(variable %in% names(parameters))
  
diag = data.frame(fit1$diagnostic_summary(), id = parameters$id)
  
  data = posteriors %>% mutate(real_alpha = parameters$alpha,
                               real_delta = parameters$delta,
                               real_beta = parameters$beta,
                               real_tau = parameters$tau,
                               real_lr = parameters$lr,
                               trials = parameters$N,
                               id = parameters$id)
  return(list(data, diag))



}


N = seq(50,200,by = 50)

alpha = seq(1,3, length.out = 2)

lr = seq(0.2,0.6, length.out = 5)

delta  = seq(1,8,length.out = 5)

beta = seq(0.5,length.out = 1)

tau = seq(0.1,0.2, length.out = 2)

e0 = seq(0.5, length.out = 1)

parameters = expand.grid(N = N,
                         lr= lr,
                         alpha = alpha,
                         delta = delta,
                         beta = beta,
                         tau = tau,
                         e0 = e0) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)
```

```{r}
q = param_recov(data_list[[1]])


#cores = availableCores()-1

plan(multisession, workers = cores)

possfit_model = possibly(.f = param_recov, otherwise = "Error")

results <- future_map(data_list, ~possfit_model(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

error_indices <- which(results == "Error")

unique(error_indices)

results2 = results[results != "Error"]
```




```{r, fig.width = 10, fig.height=7}
params = map_dfr(results, 1)

params %>% filter(variable == "beta") %>% mutate(real_beta = as.factor(real_beta)) %>% 
        ggplot(aes(x = mean, fill = real_beta))+
        facet_grid(real_alpha~trials, labeller = label_both, scales = "free")+
        theme_classic()+
        geom_density(aes(y = ..scaled.., x = median, fill = real_beta), alpha = 0.75)

params %>% filter(variable == "tau") %>% mutate(real_tau = as.factor(real_tau)) %>% 
        ggplot(aes(x = mean, fill = real_tau))+
        facet_grid(real_alpha~trials, labeller = label_both, scales = "free")+
        theme_classic()+
        geom_density(aes(y = ..scaled.., x = median, fill = real_tau), alpha = 0.75)


params %>% filter(variable == "alpha") %>% mutate(real_alpha = as.factor(real_alpha)) %>% 
        ggplot(aes(x = mean, fill = real_alpha))+
        facet_wrap(variable~trials, labeller = label_both, scales = "free")+
        theme_classic()+
        geom_density(aes(y = ..scaled.., x = median, fill = real_alpha), alpha = 0.75)


params %>% filter(variable == "lr") %>% mutate(real_lr = as.factor(real_lr)) %>% 
        ggplot(aes(x = mean, fill = real_lr))+
        facet_grid(real_alpha~trials, labeller = label_both, scales = "free")+
        theme_classic()+
        geom_density(aes(y = ..scaled.., x = median, fill = real_lr), alpha = 0.75)


params %>% filter(variable == "delta") %>% mutate(real_delta = as.factor(real_delta)) %>% 
        ggplot(aes(x = mean, fill = real_delta))+
        facet_grid(real_alpha~trials, labeller = label_both, scales = "free")+        theme_classic()+
        geom_density(aes(y = ..scaled.., x = median, fill = real_delta), alpha = 0.75)



params %>% filter(variable == "delta" & real_alpha == 1) %>% mutate(real_delta = as.factor(real_delta)) %>% 
        ggplot(aes(x = mean, fill = real_delta))+
        facet_grid(real_lr~trials, labeller = label_both, scales = "free")+        theme_classic()+
        geom_density(aes(y = ..scaled.., x = median, fill = real_delta), alpha = 0.75)



########## scatter plots
params %>% filter(variable == "delta") %>% 
        ggplot(aes(x = mean, y = real_delta, col = real_alpha))+
        facet_grid(real_lr~trials, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point()+geom_abline(slope = 1, intercept = 0)+
  coord_cartesian(ylim = c(-1, 10), xlim = c(-1,10))


params %>% filter(variable == "lr") %>% 
        ggplot(aes(x = mean, y = real_lr, col = real_alpha))+
        facet_grid(real_delta~trials, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point()+geom_abline(slope = 1, intercept = 0)+
  coord_cartesian(ylim = c(0, 1), xlim = c(0,1))

```


## fit model
```{r}

seed = 1234
trials = 50
alpha = 2
delta = 0.5
beta = 0.2
tau = 0.3

parameters = data.frame(alpha,delta,beta,tau, trials)

fit_model = function(parameters){
  id = parameters$id
  
  data = rwiener(n = parameters$trials,
          alpha = parameters$alpha,
          delta = parameters$delta,
          beta = parameters$beta,
          tau = parameters$tau)
  
  data_stan = list(Nu = nrow(data %>% filter(resp == "upper")),
                   Nl = nrow(data %>% filter(resp == "lower")),
                   RTu = data %>% filter(resp == "upper") %>% .$q,
                   RTl = data %>% filter(resp == "lower") %>% .$q,
                   minRT = 0.5,
                   RTbound = 0)
  
  
  mod = cmdstanr::cmdstan_model(here::here("HDDM.stan"))
  
  
  fit <- mod$sample(
      data = data_stan,
      seed = seed,
      chains = 4,
      parallel_chains = 4,
      adapt_delta = 0.9,
      max_treedepth = 12)
  
  
  
  posteriors = as_draws_df(fit$summary()) %>% dplyr::filter(variable %in% names(parameters))
  diag = data.frame(fit$diagnostic_summary(), id)
  
  data = posteriors %>% mutate(num_div = diag$num_divergent,
                               tree_depth = diag$num_max_treedepth,
                               real_alpha = parameters$alpha,
                               real_delta = parameters$delta,
                               real_beta = parameters$beta,
                               real_tau = parameters$tau,
                               trials = parameters$trials,
                               id = id) %>% select(-contains("."))
  return(list(data, diag))
}
```

```{r}
trials = seq(10,100,by = 10)
alpha = seq(0,5,by = 1)
delta = seq(-4,4,by = 1)
beta = seq(0.1,0.9,by = 0.1)
tau = seq(0.1,0.4,by = 0.1)

parameters = expand.grid(alpha = alpha,delta = delta,beta = beta,tau = tau, trials = trials) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)
```


```{r}
#cores = availableCores()-1

plan(multisession, workers = cores)

possfit_model = possibly(.f = fit_model, otherwise = "Error")

results <- future_map(data_list, ~possfit_model(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

error_indices <- which(results == "Error")

unique(error_indices)

results2 = results[results != "Error"]
```

lets look at the divergences
```{r}
results2[[2]]

divergence = map_dfr(results2, 2)

divergence %>% median_qi(num_divergent)
```
there are none which is good now at the parameter values

```{r, fig.height=10, fig.width=10}
params = map_dfr(results2, 1)

params %>% filter(variable == "alpha") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_alpha)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_alpha))+
  facet_wrap(~trials)

```







```{r real data}

data = read.csv(here::here("~","Thermal-Pain-Learning","Analysis","Cleaned-data","TPL_df.csv"))

trajfeel2 = read.csv(here::here("~","Thermal-Pain-Learning","Analysis","Computational_modeling","trajectories","binary_response_feel_2_v2.csv"), header = F)
data$stim = as.factor(data$stim)
data$id = as.factor(data$id)

data$stim = relevel(data$stim, ref = "cold")

data1 = data %>% filter(id %in% trajfeel2$V33)
traj1 = trajfeel2 %>% filter(V33 %in% data$id)
traj1[,34] = rep(1:306,length(unique(traj1$V33)))


traj1 = traj1 %>% dplyr::rename(mu1 = V1, mu2 = V2, 
                                mu3 = V3, sa1 = V4, 
                                sa2 = V5, sa3 = V6, 
                                mu1hat = V7, mu2hat = V8, 
                                mu3hat = V9, sa1hat = V10, 
                                sa2hat = V11, sa3hat = V12, 
                                weight_v_1 = V13, weight_v_2 = V14, 
                                weight_v_3 = V15, weight_w_1 = V16, 
                                weight_w_2 = V17, volatility_pe1 = V18, 
                                volatility_pe2 = V19, volatility_pe3 = V20, 
                                update_ud_1 = V21, update_ud_2 = V22, 
                                update_ud_3 = V23, pweights_on_pe1 = V24, 
                                pweights_on_pe2 = V25, pweights_on_pe3 = V26, 
                                pwpe1 = V27, pwpe2 = V28, pwpe3 = V29, 
                                learn_rate1 = V30, learn_rate2 = V31, 
                                learn_rate3 = V32, id = V33, 
                                trial = V34)

traj1$id = as.factor(traj1$id)
df = inner_join(data1,traj1, by = c("id","trial"))

df$burnbeta = df$vasResp_3/100
df$coldbeta = df$vasResp_1/100
df$warmbeta = df$vasResp_2/100





df$u = ifelse(df$cue == "low-tone" & df$stim == "TGI", a <- 1-(df$vasResp_1/(df$vasResp_1+df$vasResp_2)),
              ifelse(df$cue == "high-tone" & df$stim == "TGI", a <- (df$vasResp_1/(df$vasResp_1+df$vasResp_2)),
                     ifelse(df$cue == "low-tone" & df$stim == "cold", a <- 0, 
                            ifelse(df$cue == "high-tone" & df$stim == "warm", a <- 0,
                                   ifelse(df$cue == "low-tone" & df$stim == "warm", a <- 1,
                                          ifelse(df$cue == "high-tone" & df$stim == "cold", a <- 1, a <- 0.1))))))

df$predResp2 = ifelse(df$cue == "low-tone" & df$predResp == "cold", a <- 0, 
                      ifelse(df$cue == "high-tone" & df$predResp == "warm", a <- 0,
                             ifelse(df$cue == "low-tone" & df$predResp == "warm", a <- 1,
                                    ifelse(df$cue == "high-tone" & df$predResp == "cold", a <- 1, a <- NaN))))

df1 = df

df = df1 %>% filter(id == 345)

df = df %>% mutate(predRT = ifelse(predRT < 0.015,0.2,predRT))


#write.csv(df, here::here("df.csv"))


df = df %>% dplyr::select(u,predRT,predResp2, mu1hat, trial,desired_prob) %>% mutate(u = ifelse(u>=0.5,1,0))

df = na.omit(df)

df$trial = 1:nrow(df)

df %>% ggplot(aes(x = trial, y = mu1hat))+geom_line()+geom_point(aes(x = trial, y = u))+geom_line(aes(x = trial, y = desired_prob), col = "red")+theme_classic()



data_stan = list(Nu = nrow(df %>% filter(predResp2 == 1)),
                 Nl = nrow(df %>% filter(predResp2 == 0)),
                 RTu = df %>% filter(predResp2 == 1) %>% .$predRT,
                 RTl = df %>% filter(predResp2 == 0) %>% .$predRT,
                 minRT = min(df$predRT),
                 run_estimation = 1,
                 trials = nrow(df),
                 u = df$u,
                 indexupper = df %>% filter(predResp2 == 1) %>% .$trial,
                 indexlower = df %>% filter(predResp2 == 0) %>% .$trial,
                 resp = c(df$predResp2,0))




mod = cmdstanr::cmdstan_model(here::here("RLDDM.stan"))


fit1 <- mod$sample(
    data = data_stan,
    chains = 4,
    iter_warmup = 500,
    iter_sampling = 500,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 10
    )


mod2 = cmdstanr::cmdstan_model(here::here("RL.stan"))

fit2 <- mod2$sample(
    data = data_stan,
    chains = 4,
    iter_warmup = 500,
    iter_sampling = 500,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12,
    refresh = 10
)

fit
fit2



fit_rt_comb = fit1$summary() %>% filter(grepl("out\\[\\d+,1\\]", variable))
fit_rt_sep = fit2$summary() %>% filter(grepl("out\\[\\d+,1\\]", variable))

fit_rt_comb %>% ggplot(aes(x = mean))+geom_histogram()+geom_histogram(data = fit_rt_sep,fill = "red",alpha = 0.5)

as_draws_df(fit1$draws()) %>% select(matches("out\\[\\d+,1\\]")) %>% pivot_longer(everything()) %>% group_by(name) %>% summarize(mean = mean(value), sd = sd(value)) %>% ggplot(aes(x = 1:nrow(.), y = mean))+geom_point()

as_draws_df(fit2$draws()) %>% select(matches("out\\[\\d+,1\\]"))

fitexpectations_comb = fit1$summary() %>% filter(grepl("expect\\[\\d+\\]", variable))
fitexpectations_sep = fit2$summary() %>% filter(grepl("expect\\[\\d+\\]", variable))

fitexpectations_comb %>% ggplot(aes(x = 1:nrow(.), y = mean))+geom_line()+geom_line(data = fitexpectations_sep,col = "red")


fitexpectations_comb = fit1$summary() %>% filter(grepl("expect\\[\\d+\\]", variable))
fitexpectations_sep = fit2$summary() %>% filter(grepl("expect\\[\\d+\\]", variable))


library(posterior)
as_draws_df(fit1$draws(variables = "lr")) %>% ggplot(aes(x = lr))+geom_histogram(fill = "red", alpha = 0.5)+theme_classic()+geom_histogram(data = as_draws_df(fit2$draws(variables = "lr")), aes(x = lr), fill = "lightblue", alpha = 0.5)

```




```{r}
ids = c(265,267)

df = df1 %>% filter(id %in% ids)

df = df %>% mutate(predRT = ifelse(predRT < 0.015,0.2,predRT))


df[is.na(df)] <- 1

df$u = as.numeric(df$u)

df = df %>% dplyr::select(u,predRT,predResp2, mu1hat, trial,desired_prob,id,stim) %>% mutate(u = ifelse(stim == "TGI",1,ifelse(u == 1,1,0)))



df$id = as.numeric(as.factor(as.numeric(df$id)))


data_stan = list(n_subjects = 2,
                 subject_Nu = df %>% filter(u == 1) %>% group_by(id) %>% summarize(n = n()) %>% .$n,
                 subject_Nl = df %>% filter(u == 0) %>% group_by(id) %>% summarize(n = n()) %>% .$n,
                 total_trial = nrow(df),
                 subject = df$id,
                 RTu = df %>% filter(u == 1) %>% group_by(id) %>% .$predRT,
                 RTl = df %>% filter(u == 0) %>% group_by(id) %>% .$predRT,
                 minRT = df %>% group_by(id) %>% summarize(min = min(predRT)) %>% .$min,
                 run_estimation = 1,
                 u = df$u,
                 indexupper = df %>% filter(u == 1) %>% .$trial,
                 indexlower = df %>% filter(u == 0) %>% .$trial,
                 resp = c(c(df %>% filter(id == 1) %>% .$predResp2,1),c(df %>% filter(id == 2) %>% .$predResp2,1)))




mod = cmdstanr::cmdstan_model(here::here("HRLDMM.stan"))


fit <- mod$sample(
    data = data_stan,
    chains = 4,
    iter_warmup = 500,
    iter_sampling = 500,
    parallel_chains = 4,
    adapt_delta = 0.9,
    max_treedepth = 12)


```

