---
title: "ERLDMM"
output:
  pdf_document: default
  html_document: default
date: "2023-10-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(brms, tidyverse,RWiener, tidybayes, posterior, furrr,gganimate, cmdstanr, bayesplot, loo, patchwork, extraDistr, flextable)

```

## R Markdown


```{r ERLDMM}
agent_expect = function(parameters){
  
  N = 200
  
  u = c()
  for(i in 1:(N/100)){
    u1 = c(rbinom(25,1,0.8),rbinom(25,1,0.2),rbinom(25,1,0.8),rbinom(25,1,0.5))
    u = c(u,u1)
  }

  N = length(u)
  
  sens_c = parameters$sens_c
  sens_w = parameters$sens_w
  
  stim = rbinom(N,1,0.5)
  cue = ifelse(stim == u, 1,0)
  
  stim2 = ifelse(stim == 1, "cold","warm")
  cue2 = ifelse(cue == 1, "high-tone","low-tone")
  
  
  alpha = parameters$alpha
  delta = parameters$delta
  beta = parameters$beta
  tau = parameters$tau
  lr = parameters$lr
#  zeta = parameters$zeta
  e0 = parameters$e0
  nu = parameters$nu
  prec_per = parameters$prec_per
  
  expectation = array(NA, N+1)
  uncertainty = array(NA, N)
  real_resp = array(NA, N)
  mu_per = array(NA, N)
  percept = array(NA, N)
  belief_to_stim_cold = array(NA, N)
  
  
  expectation[1] = e0
  
  resp = data.frame()
  for(i in 1:N){
    
    belief_to_stim_cold[i] = ifelse(cue[i] == 1, expectation[i], 1-expectation[i])
    
    if(stim[i] == 1){ #1 is cold -1 is warm
      mu_per[i] = brms::inv_logit_scaled(sens_c+((1-nu)*stim[i]+nu*(belief_to_stim_cold[i]-0.5)))
    }else{
      mu_per[i] = brms::inv_logit_scaled(sens_w+(-((1-nu)*(-stim[i])+nu*(belief_to_stim_cold[i]-0.5))))
    }
    
    percept[i] = extraDistr::rprop(1, prec_per, mu_per[i])
    
    uncertainty[i] = (expectation[i]-(1-expectation[i]))*delta
    
    resp1 = rwiener(n = 1,
          alpha = alpha,
          delta = uncertainty[i],
          beta = beta,
          tau = tau)
    
    expectation[i+1] = expectation[i]+lr*(u[i]-expectation[i])
    
    #real_resp[i] = rbinom(1,1,(expectation[i]^zeta)/((expectation[i]^zeta)+(1-expectation[i])^zeta))
      
    resp = rbind(resp,resp1)
  }
  
  resp$u = u
  resp$expectation = expectation[1:N]
  resp$uncertainty = uncertainty[1:N]
  #resp$real_resp = real_resp
  
  resp$trial = 1:N
  
  #resp %>% ggplot(aes(x = trial, y = expectation))+geom_line()+geom_point(aes(x = trial, y = u))
  
  resp = resp %>% mutate(resp2 = ifelse(resp == "upper",1,0))
  
  resp = resp %>% mutate(correct = ifelse(resp2 == u, 1, 0))
  
  #resp$percept = ifelse(percept < 0.001, 0.001, ifelse(percept > 0.999, 0.999, percept))
  
  resp$percept = percept
  
  resp$belief_to_stim_cold = belief_to_stim_cold
  
  resp$stim = stim
  
  resp$cue = cue
  
  resp$stim2 = stim2
  
  resp$cue2 = cue2
  
  
  resp$lr = lr
  resp$alpha = alpha
  resp$beta = beta
  resp$tau = tau
  resp$delta = delta
  resp$nu = nu
  resp$prec_per = prec_per
  resp$sens_w = sens_w
  resp$sens_c = sens_c
  

  
  return(resp)
}
```


```{r}
resp = agent_expect(parameters = data.frame(
                              alpha = 2,
                              lr = 0.2,
                              delta = 2,
                              beta = 0.5,
                              sens_c = 1,
                              sens_w = 1,
                              tau = 0.1,
                              e0 = 0.5,
                              nu = 1,
                              prec_per = 20,
                              id = 2))

resp %>% 
  ggplot(aes(x = belief_to_stim_cold, y = percept, col = stim2))+
  geom_point()+
  geom_smooth(method = "lm")

resp %>% 
  ggplot(aes(x = expectation, y = percept, col = stim2))+
  geom_point()+
  geom_smooth(method = "lm")


resp %>% ggplot(aes(x = expectation, y = q))+
  geom_point()+
  geom_smooth()

resp %>% ggplot()+
  geom_point(aes(x = trial, y = resp2))+
  geom_line(aes(x = trial, y = expectation))+
  theme_classic()

resp %>% ggplot()+
  geom_boxplot(aes(x = as.factor(stim2), y = percept))+
  theme_classic()


```


```{r}

data_stan = list(RT = resp %>% .$q,
                 stim = resp %>% .$stim,
                 cue = resp %>% .$cue,
                 percept = resp %>% .$percept,
                 minRT = min(resp$q),
                 trials = nrow(resp),
                 u = resp$u,
                 resp = c(resp$resp2,0))




mod = cmdstanr::cmdstan_model(here::here("stan_scripts","ERLDDM.stan"))



fit1 <- mod$sample(
    data = data_stan,
    chains = 4,
    parallel_chains = 4,
    adapt_delta = 0.8,
    max_treedepth = 10,
    refresh = 100
    )



variables = c("delta","lr","alpha","beta","tau","nu","prec_per","sens_w","sens_c")
# mcmc_pairs(fit1$draws(variables = variables),
#            np = nuts_params(fit1), pars = variables,
#            off_diag_args = list(size = 0.75))

mcmc_trace(fit1$draws(variables = variables))+
  theme_classic()

```


```{r}
flextable::flextable(data.frame(fit1$summary()) %>% 
                       mutate_if(is.numeric, round, digits = 2) %>% 
                       head(10))
```


```{r}
variables = c("delta","lr","alpha","beta","tau","nu","prec_per","sens_w","sens_c")
posteriors = as_draws_df(fit1$draws(variables = variables)) %>% 
  select(variables) %>% 
  pivot_longer(everything())%>% mutate(posterior = T)

prior_variables = paste0("prior_",variables)
priors = as_draws_df(fit1$draws(variables = prior_variables)) %>% 
  select(prior_variables) %>% 
  pivot_longer(everything()) %>% mutate(posterior = F) %>% 
  mutate(name = gsub("prior_","",name))


rbind(priors,posteriors) %>% 
  ggplot(aes(x = value, fill = posterior))+
  geom_histogram(alpha = 0.75, position = 'identity', col = "black")+
  facet_wrap(~name, scales = "free")+
  theme_classic()+
  geom_vline(data = data.frame(name = variables,
                               value = as.vector(unlist(resp %>% select(variables) %>% 
                                                          slice(1)))),
             aes(xintercept = value), linetype = 2)



```


```{r}
draww = rbinom(1,4000,extraDistr::rprop(1,1,0.5))

deltas = as_draws_df(fit1$draws()) %>% select(matches("deltat\\[\\d+\\]")) %>% 
  mutate(draw = 1:nrow(.)) %>% slice(draww) %>% 
  pivot_longer(-draw, values_to = "deltat",names_to = "trial")%>%
  mutate(trial = gsub(".*\\[(\\d+).*\\]", "\\1", trial))



parameters = as_draws_df(fit1$draws()) %>% 
  select(matches(c("alpha","tau","beta"))) %>% 
  mutate(tau_raw = NULL) %>% 
  mutate(draw = 1:nrow(.)) %>% slice(draww)


df = inner_join(deltas, parameters)

resp %>% ggplot(aes(x = expectation, y = q))+
  geom_point()+
  theme_classic()+
  geom_smooth()

df %>% select(-matches("^prior_")) %>% 
  rowwise() %>% 
  mutate(predictedRT = RWiener::rwiener(1,alpha,tau,beta,deltat)[[1]],predictedresp = RWiener::rwiener(1,alpha,tau,beta,deltat)[[2]]) %>% 
  ggplot(aes(deltat,predictedRT))+geom_point()+
  theme_classic()+
  geom_smooth()



resp %>% ggplot(aes(x = uncertainty, y = q, col = resp))+
  geom_point()+
  theme_classic()+
  geom_smooth()

df %>% rowwise() %>% mutate(predictedRT = RWiener::rwiener(1,alpha,tau,beta,deltat)[[1]],predictedresp = RWiener::rwiener(1,alpha,tau,beta,deltat)[[2]]) %>% 
  ggplot(aes(deltat,predictedRT, col = predictedresp))+geom_point()+
  theme_classic()+
  geom_smooth()
```

```{r rt pp}
library(posterior)

n_check = 25

get_pp = function(draww){
  draww = draww$draww
  deltas = as_draws_df(fit1$draws()) %>% select(matches("deltat\\[\\d+\\]")) %>% 
    mutate(draw = 1:nrow(.)) %>% slice(draww) %>% 
    pivot_longer(-draw, values_to = "deltat",names_to = "trial")%>%
    mutate(trial = gsub(".*\\[(\\d+).*\\]", "\\1", trial))
  
  
  
  parameters = as_draws_df(fit1$draws()) %>% select(matches(c("alpha","tau","beta"))) %>% mutate(tau_raw = NULL) %>% 
    mutate(draw = 1:nrow(.)) %>% slice(draww)
  
  
  df = inner_join(deltas, parameters) %>% 
    rowwise() %>% 
    mutate(predictedRT = RWiener::rwiener(1,alpha,tau,beta,deltat)[[1]],
           predictedresp = RWiener::rwiener(1,alpha,tau,beta,deltat)[[2]],
           draw = draww)
  return(list(df))
}

draww = rbinom(n_check,4000,extraDistr::rprop(n_check,1,0.5))


parameters = expand.grid(draww = draww) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)

results <- future_map(data_list, ~get_pp(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

rts = map_dfr(results,1)

rts %>% ggplot()+
  geom_density(aes(x = predictedRT, group = draw),col = "lightblue")+
  geom_density(data = resp, aes(x = q),col = "red")+
  theme_classic()


rts %>% mutate(predictedresp = ifelse(predictedresp == "lower", 0, 1)) %>%
  ggplot()+
  geom_bar(aes(x = predictedresp-0.2),fill = "lightblue", alpha = 0.5, width = 0.2)+
  geom_bar(data = resp, aes(x = resp2),fill = "red", alpha = 0.5, width = 0.2)+
  theme_classic()+
  facet_wrap(~draw)

```

```{r resp pp}
library(posterior)

n_check = 25

get_pp_percept = function(draww){
  draww = draww$draww
  pred_percept = as_draws_df(fit1$draws()) %>% select(matches("pred_percept\\[\\d+\\]")) %>% 
    mutate(draw = 1:nrow(.)) %>% slice(draww) %>% 
    pivot_longer(-draw, values_to = "pred_percept",names_to = "trial")%>%
    mutate(trial = gsub(".*\\[(\\d+).*\\]", "\\1", trial))
  
  return(list(pred_percept))
}

draww = rbinom(n_check,4000,extraDistr::rprop(n_check,1,0.5))


parameters = expand.grid(draww = draww) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)

results <- future_map(data_list, ~get_pp_percept(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))

percepts = map_dfr(results,1)

percepts %>% ggplot()+
  geom_density(aes(x = pred_percept, group = draw),col = "lightblue")+
  geom_density(data = resp, aes(x = percept),col = "red")+
  theme_classic()
```



```{r}
parameter_recovery_expect = function(parameters){
  
  resp = agent_expect(parameters)
  
  
  data_stan = list(RT = resp %>% .$q,
                 stim = resp %>% .$stim,
                 cue = resp %>% .$cue,
                 percept = resp %>% .$percept,
                 minRT = min(resp$q),
                 trials = nrow(resp),
                 u = resp$u,
                 resp = c(resp$resp2,0))
  
  
  
  
  mod = cmdstanr::cmdstan_model(here::here("stan_scripts","ERLDDM.stan"))


  
  fit1 <- mod$sample(
      data = data_stan,
      chains = 4,
      parallel_chains = 4,
      adapt_delta = 0.9,
      iter_sampling = 1000,
      iter_warmup = 1000,
      init = 0,
      max_treedepth = 12,
      refresh = 0
      )


  posteriors = as_draws_df(fit1$summary(names(parameters)[c(1:7,9,10)])) %>% dplyr::filter(variable %in% names(parameters))
  
  diag = data.frame(fit1$diagnostic_summary(), id = parameters$id)
  
  data = posteriors %>% mutate(real_alpha = parameters$alpha,
                               real_delta = parameters$delta,
                               real_beta = parameters$beta,
                               real_tau = parameters$tau,
                               real_lr = parameters$lr,
                               trials = parameters$trials,
                               real_prec_per = parameters$prec_per,
                               real_nu = parameters$nu,
                               real_sens_w = parameters$sens_w,
                               real_sens_c = parameters$sens_c,
                               id = parameters$id)
  return(list(data, diag))
  
}
```

# parameter recovery
```{r}

alpha = seq(1,3, length.out = 3)

lr = seq(0.1,0.7, length.out = 7)

delta  = seq(-2,2,length.out = 4)

beta = seq(0.3,0.8,length.out = 1)

tau = seq(0.1,0.3, length.out = 3)

e0 = seq(0.5, length.out = 1)

prec_per = seq(1,20, length.out = 5)

nu = seq(-2,2, length.out = 4)

sens_w = seq(-2,2, length.out = 1)

sens_c = seq(-2,2, length.out = 1)

replicate = 1

parameters = expand.grid(lr= lr,
                         alpha = alpha,
                         delta = delta,
                         beta = beta,
                         tau = tau,
                         prec_per = prec_per,
                         nu = nu,
                         trials = 200,
                         sens_w = sens_w,
                         sens_c = sens_c,
                         e0 = e0,
                         replicate = replicate) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(parameters, parameters$id)
```


```{r}
qq = parameter_recovery_expect(data_list[[50]])

# 
cores = availableCores()-1
# 
plan(multisession, workers = cores)
# 
possfit_model = possibly(.f = parameter_recovery_expect, otherwise = "Error")
# 
results <- future_map(data_list, ~possfit_model(.x), .progress = TRUE, .options = furrr_options(seed = TRUE))
# 
error_indices <- which(results == "Error")

unique(error_indices)

results2 = results[results != "Error"]

```


```{r, fig.height=10, fig.width=10}
load(here::here("report","ERLDMM","workspace.RData"))


params = map_dfr(results2, 1)

params %>% filter(variable == "alpha") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_alpha)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_alpha))+
  facet_wrap(~trials)+coord_cartesian(ylim = c(0,50))

params %>% filter(variable == "delta") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_delta)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_delta))+
  facet_wrap(~trials)+
  coord_cartesian(xlim = c(-4,4))

params %>% filter(variable == "tau") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_tau)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_tau))+
  facet_wrap(~trials)


params %>% filter(variable == "beta") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_beta)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_beta))+
  facet_wrap(~trials)

params %>% filter(variable == "lr") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_lr)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_lr))+
  facet_wrap(~trials)


params %>% filter(variable == "nu") %>% 
  ggplot(aes(x = mean, fill = as.factor(real_nu)))+
  geom_density(alpha = 0.5)+
  theme_classic()+
  geom_vline(aes(xintercept = real_nu))+
  facet_wrap(~trials)


```


```{r, fig.height=10, fig.width=10}

params %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  filter(variable == "delta") %>% 
        ggplot(aes(x = mean, y = real_delta, col = trials))+
        facet_grid(~real_alpha, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point(aes())+geom_abline(slope = 1, intercept = 0)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


params %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  filter(variable == "alpha") %>% 
        ggplot(aes(x = mean, y = real_alpha, col = trials))+
        facet_grid(~real_delta, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point(aes())+geom_abline(slope = 1, intercept = 0)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



params %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  filter(variable == "nu") %>% 
        ggplot(aes(x = mean, y = real_nu, col = trials))+
        facet_grid(~real_prec_per, labeller = label_both, scales = "free")+
        theme_classic()+
  geom_point(aes())+geom_abline(slope = 1, intercept = 0)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



params %>% 
  mutate_if(is.numeric, round, digits = 2) %>% 
  filter(variable == "lr") %>% 
        ggplot(aes(x = mean, y = real_lr, col = trials))+
        theme_classic()+
  geom_point(aes())+geom_abline(slope = 1, intercept = 0)+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```


