---
title: "parameter recovery"
output: html_document
date: "2023-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,RWiener, tidybayes, posterior, furrr,gganimate, cmdstanr, bayesplot, loo, patchwork)

```

## R Markdown


```{r}

source(here::here("report","RLDDM","parameter recovery","simulations.R"))

N = seq(50,200,by = 50)

alpha = seq(1,3,by = 1)
beta = seq(0.4,0.6,by = 0.1)
beta = 0.5
delta = seq(0,4,by = 1)
tau_raw = seq(0.1,0.3, by = 0.1)
tau_raw = 0.2
lr = seq(0.1,0.6, by = 0.1)


params = expand.grid(N = N,
                     lr = lr,
                     alpha = alpha,
                     beta = beta,
                     delta = delta,
                     tau_raw = tau_raw) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(params, params$id)

fit_pr_to_simple_rw(data_list[[250]])

# cores = availableCores()
# 
plan(multisession, workers = 8)
# 
# 
possfit_model = possibly(.f = fit_pr_to_simple_rw, otherwise = "Error")
# 
possfit_model(data_list[[1]])
# 
# 

results <- future_map(data_list[1:5], ~possfit_model(.x),
                       .progress = TRUE,
                       .options = furrr_options(seed = TRUE))



error_indices <- which(results == "Error")
results[[1]]
unique(error_indices)

results2 = results[results != "Error"]

divergence = purrr::map_dfr(results2,3)

divergence %>% median_qi(num_divergent)

divergence%>% ggplot(aes(x = num_divergent))+geom_histogram()

```


# Visuaalization


# Visuaalization

# Parameter recovery visualization
```{r}
# linear model fit
load(here::here("report","RLDDM","parameter recovery","workspace","results_rlddm_vs_rl.RData"))

  results2 = results
  
  divergence = map_dfr(results2, 2)
  
  divergence %>%
    pivot_longer(cols = c(num_divergent, num_max_treedepth)) %>%
    ggplot(aes(x = value))+facet_wrap(~name)+geom_histogram()

    divergence = map_dfr(results2, 4)
  
  divergence %>%
    pivot_longer(cols = c(num_divergent, num_max_treedepth)) %>%
    ggplot(aes(x = value))+facet_wrap(~name)+geom_histogram()

  # summary(divergence$num_divergent)
  # 
  # 
  # ids_no_div = unique(divergence %>% filter(num_divergent == 0) %>% .$id)
  # 
  
  results = map_dfr(results2, 1)
  
  plot_list <- list()
  
  results = results %>% mutate(across(all_of(contains("real_")), as.factor))
  
  
    for(variables in unique(results$variable)){
  
  
      p = results %>%
        mutate(across(all_of(contains("real_")), as.factor)) %>% 
        filter(variable == variables) %>%
        mutate(real = .[[paste0("real_", variables)]]) %>% 
        mutate(real2 = as.numeric(as.character(real))) %>% 
        rename(Trial_number = N) %>% 
        ggplot(aes(x = mean, fill = real))+
        geom_histogram(col = "black", alpha = 0.5, position="identity")+
        theme_classic()+
        geom_vline(aes(xintercept = real2), alpha = 0.5, linetype = 2)+
        facet_wrap(~Trial_number, labeller = label_both, ncol = 4)+
        theme(legend.position = "top")+
        ggtitle(paste0(variables))

      
      plot_list[[variables]] <- p
    }

plot_list[["lr"]]
plot_list[["alpha"]]
plot_list[["delta"]]
plot_list[["beta"]]
plot_list[["tau"]]

```


```{r}
results = map_dfr(results2, 3)
  
  results = results %>% mutate(across(all_of(contains("real_")), as.factor))
  
   results %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    rename(Trial_number = N) %>% 
    ggplot(aes(x = mean, fill = real))+
    geom_histogram(col = "black", alpha = 0.5, position="identity")+
    theme_classic()+
    geom_vline(aes(xintercept = real2), alpha = 0.5, linetype = 2)+
    facet_wrap(~Trial_number, labeller = label_both, ncol = 4)+
    theme(legend.position = "top")+
    ggtitle(paste0("lr"))
```


# Difference plots

```{r, fig.width=10, fig.height=7}

results = map_dfr(results2, 3)

rw = results %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
    ggplot(aes(x = dif, fill = real))+
    geom_vline(aes(xintercept = 0), alpha = 0.5, linetype = 2)+
    geom_histogram(col = "black", alpha = 0.5, position="identity")+
    theme_classic()+
    facet_wrap(~Trial_number, labeller = label_both, ncol = 4)+
    theme(legend.position = "top")+
    ggtitle(paste0("lr (RW)"))





results = map_dfr(results2, 1)

ddm = results %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
    ggplot(aes(x = dif, fill = real))+
    geom_vline(aes(xintercept = 0), alpha = 0.5, linetype = 2)+
    geom_histogram(col = "black", alpha = 0.5, position="identity")+
    theme_classic()+
    facet_wrap(~Trial_number, labeller = label_both, ncol = 4)+
    theme(legend.position = "top")+
    ggtitle(paste0("lr (DDM)"))


rw/ddm


results = map_dfr(results2, 1)

results %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
    ggplot(aes(x = dif, y = real_delta, col = real))+
    geom_vline(aes(xintercept = 0), alpha = 0.5, linetype = 2)+
    geom_point(alpha = 0.5, position="identity")+
    theme_classic()+
    facet_wrap(~Trial_number, labeller = label_both, ncol = 4)+
  scale_x_continuous(lim = c(-0.6,0.6),breaks = c(-0.6,-0.3,0,0.3,0.6),labels = c(-0.6,-0.3,0,0.3,0.6))+
    theme(legend.position = "top")+
    ggtitle(paste0("lr (DDM)"))


results = map_dfr(results2, 3)

results %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
    ggplot(aes(x = dif, y = real_delta, col = real))+
    geom_vline(aes(xintercept = 0), alpha = 0.5, linetype = 2)+
    geom_point(alpha = 0.5, position="identity")+
    theme_classic()+
    facet_wrap(~Trial_number, labeller = label_both, ncol = 4)+
  scale_x_continuous(lim = c(-0.6,0.6),breaks = c(-0.6,-0.3,0,0.3,0.6),labels = c(-0.6,-0.3,0,0.3,0.6))+
    theme(legend.position = "top")+
    ggtitle(paste0("lr (RW)"))




results_ddm = map_dfr(results2, 1) %>% mutate(fitted = "DDM") %>% dplyr::select(id,mean,real_lr,variable,N,fitted,real_delta,real_alpha)
results_rw = map_dfr(results2, 3) %>% mutate(fitted = "RW") %>% dplyr::select(id,mean,real_lr,variable,N,fitted,real_delta, real_alpha)




rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
  group_by(real_delta, Trial_number,real,fitted) %>% 
  summarise(mean = mean(dif), sd = sd(dif)) %>% 
  mutate(real = as.numeric(as.character(real))) %>% 
  mutate(real = ifelse(fitted == "DDM", real-0.04,real)) %>% 
  ggplot(aes(x = mean, y = real, xmin = mean-2*sd, xmax = mean+2*sd, col = fitted))+
  geom_pointrange()+
  facet_wrap(Trial_number~real_delta, labeller = label_both)+
  theme_classic()


rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
  group_by(real_delta, Trial_number,real,fitted,real_alpha) %>% 
  summarise(mean = mean(dif), sd = sd(dif)) %>% 
  mutate(real = as.numeric(as.character(real))) %>% 
  mutate(real = ifelse(fitted == "DDM", real-0.04,real)) %>% 
  ggplot(aes(x = mean, y = real, xmin = mean-2*sd, xmax = mean+2*sd, col = fitted))+
  geom_pointrange()+
  facet_grid(Trial_number~real_delta+real_alpha, labeller = label_both)+
  theme_classic()


```


```{r}
dd = rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real)), real_delta = as.numeric(as.character(real_delta))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N)

library(gamlss)

ss = gamlss::gamlss(mean ~ fitted+real,
               sigma.formula = ~ fitted+real,
               data = dd)

summary(ss)

ss = gamlss::gamlss(mean ~ fitted*real,
               sigma.formula = ~ fitted*real,
               data = dd)

summary(ss)


ss = gamlss::gamlss(mean ~ fitted*real2*real_delta+Trial_number,
               sigma.formula = ~ fitted*real*real_delta+Trial_number,
               data = dd)

summary(ss)


plot(ggeffects::ggpredict(ss, terms = c("real2","fitted","real_delta")))+
  geom_abline(slope = 1, intercept = 0, linewidth = 1)+
  geom_point()


```


```{r}

source(here::here("report","RLDDM","parameter recovery","simulations.R"))

samples = 10000
N = sample(c(50,100,150,200,250,300),samples, replace = T)

alpha = runif(samples,0.5,5)

beta = runif(samples,0.2,0.8)

delta = runif(samples,0,5)
tau_raw = runif(samples,0.1,0.5)

lr = runif(samples,0,0.8)


params = data.frame(N = N,
                     lr = lr,
                     alpha = alpha,
                     beta = beta,
                     delta = delta,
                     tau_raw = tau_raw) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(params, params$id)

#fit_pr_to_simple_rw(data_list[[250]])

 cores = availableCores()
# 
plan(multisession, workers = availableCores())
# 
# 
possfit_model = possibly(.f = fit_pr_to_simple_rw, otherwise = "Error")
# 
#possfit_model(data_list[[1]])
# 
# 

results <- future_map(data_list, ~possfit_model(.x),
                       .progress = TRUE,
                       .options = furrr_options(seed = TRUE))



error_indices <- which(results == "Error")
results[[1]]
unique(error_indices)

results2 = results[results != "Error"]

divergence = purrr::map_dfr(results2,3)

divergence %>% median_qi(num_divergent)

divergence%>% ggplot(aes(x = num_divergent))+geom_histogram()
```



```{r}
load(here::here("report","RLDDM","parameter recovery","workspace","results_rlddm_vs_rl_contin2.RData"))



error_indices <- which(results == "Error")
results[[1]]
unique(error_indices)

results2 = results[results != "Error"]


divergence = map_dfr(results2, 4)

divergence %>%
  pivot_longer(cols = c(num_divergent, num_max_treedepth)) %>%
  ggplot(aes(x = value))+facet_wrap(~name)+geom_histogram()




results_ddm = map_dfr(results2, 1) %>% mutate(fitted = "DDM") %>% dplyr::select(id,mean,real_lr,variable,N,fitted,real_delta,real_alpha, real_beta, real_tau)
results_rw = map_dfr(results2, 3) %>% mutate(fitted = "RW") %>% dplyr::select(id,mean,real_lr,variable,N,fitted,real_delta, real_alpha, real_beta, real_tau)




rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
  ggplot(aes(x = dif, fill = fitted))+geom_histogram(col = "black", alpha = 0.6,position = "identity")+facet_wrap(~Trial_number)


rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
  mutate(real_delta2 = cut(as.numeric(as.character(real_delta)), breaks = 0:5)) %>% 
  mutate(real_delta = as.numeric(as.character(real_delta))) %>% 
  ggplot(aes(x = dif, col = fitted, y = real_delta))+geom_point(alpha = 0.6,position = "identity")+facet_wrap(~Trial_number)+
  scale_y_continuous(breaks = seq(0,5,by = 1), labels = seq(0,5,by = 1))



rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
  mutate(real_delta2 = cut(as.numeric(as.character(real_delta)), breaks = 0:5)) %>% 
  mutate(real_lr = as.numeric(as.character(real_lr))) %>% 
  ggplot(aes(x = dif, col = fitted, y = real_lr))+geom_point(alpha = 0.6,position = "identity")+facet_wrap(~Trial_number)+
  scale_y_continuous(breaks = seq(0,1,by = 0.2), labels = seq(0,1,by = 0.2))


```


```{r}
dd = rbind(results_rw,results_ddm) %>%
    mutate(across(all_of(contains("real_")), as.factor)) %>% 
    filter(variable == "lr") %>%
    mutate(real = .[[paste0("real_", "lr")]]) %>% 
    mutate(real2 = as.numeric(as.character(real))) %>% 
    mutate(dif = mean-real2) %>% 
    rename(Trial_number = N) %>% 
    mutate(real = as.numeric(as.character(real)),
           real_delta = as.numeric(as.character(real_delta)),
           real_alpha = as.numeric(as.character(real_alpha)),
           )

  


ss = gamlss::gamlss(mean ~ fitted+real,
               sigma.formula = ~ fitted+real,
               data = dd)

summary(ss)

ss = gamlss::gamlss(mean ~ fitted*real,
               sigma.formula = ~ fitted*real,
               data = dd)

summary(ss)
dd1 = dd %>% filter(real_delta > 1, real_delta < 2)
ss = gamlss::gamlss(mean ~ fitted*real*Trial_number,
               sigma.formula = ~ fitted*real*Trial_number,
               data = dd1)

summary(ss)

plot(ggeffects::ggpredict(ss, terms = c("real","fitted","Trial_number")))+
  geom_abline(slope = 1, intercept = 0, linewidth = 1)+
  geom_point()

plot(ggeffects::ggpredict(ss, terms = c("real","fitted","Trial_number"), what = "sigma"))+
  geom_abline(slope = 1, intercept = 0, linewidth = 1)+
  geom_point()


ss = gamlss::gamlss(mean ~ fitted*real*real_delta*Trial_number*real_alpha,
               sigma.formula = ~ fitted*real*real_delta*Trial_number*real_alpha,
               data = dd)

summary(ss)


ss1 = gamlss::gamlss(mean ~ fitted*real*real_delta*Trial_number*real_alpha,
               sigma.formula = ~ fitted*real*real_delta*Trial_number*real_alpha,
               family = gamlss.dist::BE(),
               data = dd)


gamlss::Rsq(ss)
gamlss::Rsq(ss1)



gamlss::predictAll(ss, newdata = data.frame(fitted = "DDM", Trial_number = 200,real_delta = 1, real = 0.3, real_alpha = 1))
gamlss::predictAll(ss, newdata = data.frame(fitted = "RW", Trial_number = 200,real_delta = 1, real = 0.3, real_alpha = 1))




plot(ggeffects::ggpredict(ss, terms = c("real","fitted","real_delta","Trial_number"), what = "sigma"))+
  geom_abline(slope = 1, intercept = 0, linewidth = 1)+
  geom_point()


plot(ggeffects::ggpredict(ss, terms = c("real","fitted","real_delta","Trial_number")))+
  geom_point()


```


