---
title: "parameter recovery"
output: html_document
date: "2023-11-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse,RWiener, tidybayes, posterior, furrr,gganimate, cmdstanr, bayesplot, loo, patchwork)

```

## R Markdown


```{r}
source(here::here("report","RLDDM","parameter recovery","simulations.R"))

N = seq(50,200,by = 50)

alpha = seq(1,3,by = 1)
beta = seq(0.4,0.6,by = 0.1)
delta = seq(0,4,by = 1)
tau_raw = seq(0.1,0.3, by = 0.1)
lr = seq(0.1,0.6, by = 0.1)


params = expand.grid(N = N,
                     lr = lr,
                     alpha = alpha,
                     beta = beta,
                     delta = delta,
                     tau_raw = tau_raw) %>% 
  mutate(id = 1:nrow(.))

data_list <- split(params, params$id)

fit_pr(data_list[[750]])

# cores = availableCores()-1
# 
# plan(multisession, workers = cores)
# 
# 
# possfit_model = possibly(.f = fit_pr, otherwise = "Error")
# 
# possfit_model(data_list[[1]])
# 
# 
# results_linearddm <- future_map(data_list, ~possfit_model(.x),
#                        .progress = TRUE,
#                        .options = furrr_options(seed = TRUE))

```

